services:
  db:
    image: postgres:16  # Using latest version of PostgreSQL
    container_name: rust_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data  # Data persistence
    ports:
      - "5432:5432"  # Exposed port for local development, should be restricted in production

  backend:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL} 
    ports:
      - "8080:8080"
    depends_on:
      - db


networks:
  private_net:
    driver: bridge  # Ensures the db is isolated from public network
  bridge:
    external: true

volumes:
  pgdata:  # Stores the PostgreSQL data

