# Generated by Django 5.1.6 on 2025-03-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'crossword',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('definition', models.TextField()),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1)),
                ('is_blank', models.BooleanField()),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('crossword', models.ForeignKey(db_column='crossword_id', on_delete=django.db.models.deletion.CASCADE, to='litlan.crossword')),
            ],
            options={
                'db_table': 'cell',
                'unique_together': {('crossword', 'x_coord', 'y_coord')},
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('direction', models.CharField(choices=[('Vertical', 'Vertical'), ('Horizontal', 'Horizontal')], max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('crossword', models.ForeignKey(db_column='crossword_id', on_delete=django.db.models.deletion.CASCADE, to='litlan.crossword')),
            ],
            options={
                'db_table': 'hint',
                'unique_together': {('crossword', 'x_coord', 'y_coord', 'direction')},
            },
        ),
    ]
